# Generated by Django 4.1.7 on 2023-04-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/portfolio')),
                ('temoignages', models.TextField()),
            ],
        ),
    ]
