# Generated by Django 4.1.7 on 2023-04-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0004_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
    ]
