# Generated by Django 4.1.7 on 2023-05-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0006_alter_personnel_ficher_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=200)),
                ('messaage', models.CharField(max_length=500)),
            ],
        ),
    ]
