# Generated by Django 4.1.7 on 2023-05-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='pdf_projet',
            field=models.FileField(default=2, upload_to='img'),
            preserve_default=False,
        ),
    ]
