# Generated by Django 4.1.7 on 2023-05-13 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0011_projet_pdf_projet'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe_personnel', to='projet.equipe'),
        ),
        migrations.AddField(
            model_name='projet',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projet.equipe'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='personnel',
            field=models.ManyToManyField(related_name='equipes', to='projet.personnel'),
        ),
    ]
