# Generated by Django 4.1.7 on 2023-05-13 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0012_personnel_equipe_projet_equipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projet.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='projet.projet'),
        ),
    ]
